---
title: "Tildelinger Innovasjon Norge"
author: "Kristian Bysheim"
date: "2 januar 2019"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
  runtime: shiny
  
---
```{r install and load packages, cache=TRUE, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(flexdashboard, httr, highcharter, shiny,
               tidyverse, plotly, leaflet, scales)
```


```{r load data, cache=TRUE, include=FALSE}
tilsagn_url <- "https://data.innovasjonnorge.no/api/files?filename=Tildelinger.csv&container=innovasjonnorge&subfolder=tildelinger/csv"
eos_url <- "https://data.innovasjonnorge.no/api/files?filename=TildelingerEOS.csv&container=innovasjonnorge&subfolder=tildelinger/csv"
rentestotte_url <- "https://data.innovasjonnorge.no/api/files?filename=TildelingerRS.csv&container=innovasjonnorge&subfolder=tildelinger/csv"

tilsagn <- read.csv(tilsagn_url, sep = ";", stringsAsFactors = FALSE)
eos <- read.csv(eos_url, sep = ";", stringsAsFactors = FALSE)
rentestotte <- read.csv(rentestotte_url, sep = ";", stringsAsFactors = FALSE)

tilsagn %>%
    count(`Næringshovedområde`) %>%
    arrange(n) %>%
    hchart(type = "treemap", hcaes(x = `Næringshovedområde`, value = n, color = n))

mapdata <- get_data_from_map(download_map_data("https://code.highcharts.com/mapdata/countries/no/no-all.js"))

```

Tildelinger 
======================================

Column {.sidebar}
--------------------------------------
Litt tekst som forklarer hva som skjer om man endrer verdiene.

```{r select input}
selectInput("Næringshovedområde", label = "Velg næring:",
            choices = c("Vindyrking", "Strutseoppdrett"), multiple = TRUE)
selectInput("Fylke", label = "Velg fylke:",
            choices = c("Oslo", "Akershus"), multiple = TRUE)
selectInput("År", label = "Velg år",
            choices = c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"), multiple = TRUE)
selectInput("Virkemiddelgruppe", label = "Velg Virkemiddelgruppe:", choices = c("Fylkesvise BU-midler", "Landsdekkende programmer"), multiple = TRUE)
```


Column {.tabset}
--------------------------------------

### Treemap

```{r treemap næringshovedområde, echo=FALSE}
tilsagn %>%
    count(`Næringshovedområde`) %>%
    arrange(n) %>%
    hchart(type = "treemap", hcaes(x = `Næringshovedområde`, value = n, color = n))

```

### Barchart

```{r echo=FALSE}
tilsagn %>%
    count(`Næringshovedområde`) %>%
    arrange(n) %>%
    hchart(type = "bar", hcaes(x = `Næringshovedområde`, y = n))

```

### Linechart

```{r}
virkemiddel_tildelt <- tilsagn %>%
  select("Virkemiddelgruppe", "Innvilget.beløp", "Innvilget.dato")
hchart(virkemiddel_tildelt, "line",
       hcaes(x = "Innvilget.dato", 
             y = "Innvilget.beløp",
             group = "Virkemiddelgruppe")
       )
  
```

Column
---------------------------------------


```{r}
antall_tilsagn <- nrow(tilsagn)
valueBox(antall_tilsagn,
         caption = "Totalt antall tilsagn")
```



```{r, echo=FALSE}
hcmap("https://code.highcharts.com/mapdata/countries/no/no-all.js",
      data = eos, value = "Innvilget.beløp",
      joinBy = c("name", "Fylkesnavn"), name = "Tildelt", # @todo: lage variabel i tilsagn som tilsvarer hc-a2
      dataLabels = list(enabled = TRUE, format = "{point.name}"),
      borderColor = "#FAFAFA", borderwidth = 0.1,
      tooltip = list(valueDecimals = 0))
```

Side 2
========================================
```{r, echo=FALSE}
hcmap("https://code.highcharts.com/mapdata/countries/no/no-all.js") %>%
    hc_title(text = "Norge")
```


Side 3 {data-navmenu=Test}
========================================

```{r}

```


Side 4 {data-navmenu=Test}
========================================

Leaflet
========================================

